import { getAuthAccessToken } from '../../auth/tokenBroker'
import { notifySessionExpired } from '../../auth/sessionEvents'
const configuredBase=import.meta.env.VITE_API_BASE_URL||import.meta.env.NEXT_PUBLIC_API_BASE_URL||'https://bettersnap-functions-dagchpg8f0b7fjed.eastus-01.azurewebsites.net/api'
export const API_BASE_URL=configuredBase.replace(/\/$/,'')
export type ApiErrorCode='bad_request'|'unauthorized'|'forbidden'|'not_found'|'conflict'|'validation_error'|'rate_limited'|'server_error'|'unknown'
const codes:Record<number,ApiErrorCode>={400:'bad_request',401:'unauthorized',403:'forbidden',404:'not_found',409:'conflict',422:'validation_error',429:'rate_limited',500:'server_error'}
export class ApiError extends Error{constructor(public status:number,message:string,public code:ApiErrorCode=codes[status]||'unknown',public correlationId?:string,public details?:unknown){super(message);this.name='ApiError'}}
export function queryString(values:object){const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')params.set(key,String(value))});const value=params.toString();return value?`?${value}`:''}
async function parseError(response:Response){const correlationId=response.headers.get('x-correlation-id')||response.headers.get('correlation-id')||undefined;let details:unknown;let message=response.statusText||'Request failed';try{details=await response.json();if(details&&typeof details==='object'&&'message'in details)message=String((details as {message:unknown}).message)}catch{message=response.statusText||message}return new ApiError(response.status,message,codes[response.status]||'unknown',correlationId,details)}
export interface RequestOptions extends RequestInit{authenticated?:boolean}
export interface ApiResult<T>{data:T;status:number;correlationId?:string}
export async function requestWithMeta<T>(path:string,options:RequestOptions={}):Promise<ApiResult<T>>{const{authenticated=true,...init}=options;const token=authenticated?await getAuthAccessToken():null;if(authenticated&&!token){notifySessionExpired();throw new ApiError(401,'Authentication is required.','unauthorized')}const isForm=init.body instanceof FormData;const hasBody=init.body!==undefined&&init.body!==null;const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers:{...(hasBody&&!isForm?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}});if(!response.ok){if(response.status===401)notifySessionExpired();throw await parseError(response)}const correlationId=response.headers.get('x-correlation-id')||response.headers.get('correlation-id')||undefined;const data=response.status===204?undefined as T:await response.json() as T;return{data,status:response.status,correlationId}}
export async function request<T>(path:string,options:RequestOptions={}):Promise<T>{return(await requestWithMeta<T>(path,options)).data}
export const api={get:<T>(path:string)=>request<T>(path),getPublic:<T>(path:string)=>request<T>(path,{authenticated:false}),getDetailed:<T>(path:string,authenticated=true)=>requestWithMeta<T>(path,{authenticated}),post:<T>(path:string,body?:unknown)=>request<T>(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)}),postDetailed:<T>(path:string,body?:unknown)=>requestWithMeta<T>(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)}),patch:<T>(path:string,body?:unknown)=>request<T>(path,{method:'PATCH',body:JSON.stringify(body)}),delete:<T>(path:string)=>request<T>(path,{method:'DELETE'}),upload:<T>(path:string,body:FormData)=>request<T>(path,{method:'POST',body})}
