import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import { ToastProvider } from './components'
import { Router } from './lib/router'
import { AuthProvider } from './auth'
import './styles.css'
import './live.css'
import './operations.css'
import './responsive.css'
createRoot(document.getElementById('root')!).render(<StrictMode><Router><AuthProvider><ToastProvider><App/></ToastProvider></AuthProvider></Router></StrictMode>)
