import { Activity,Bot,ChevronDown,CircleDollarSign,Coins,CreditCard,FileClock,Gauge,LayoutDashboard,LogOut,Menu,Users,X,type LucideIcon } from 'lucide-react'
import { useState,type ReactNode } from 'react'
import { PERMISSIONS,useAuth,type Permission } from '../auth'
import { Link,useRouter } from '../lib/router'
const nav:{label:string;to:string;icon:LucideIcon;permission:Permission}[]=[
  {label:'Dashboard',to:'/dashboard',icon:LayoutDashboard,permission:PERMISSIONS.DASHBOARD_READ},{label:'Users',to:'/users',icon:Users,permission:PERMISSIONS.USERS_READ},{label:'AI Jobs',to:'/jobs',icon:Bot,permission:PERMISSIONS.JOBS_READ},{label:'Payments',to:'/payments',icon:CircleDollarSign,permission:PERMISSIONS.BILLING_READ},{label:'Subscriptions',to:'/subscriptions',icon:CreditCard,permission:PERMISSIONS.SUBSCRIPTIONS_READ},{label:'Credits',to:'/credits',icon:Coins,permission:PERMISSIONS.CREDITS_READ},{label:'System Health',to:'/system-health',icon:Activity,permission:PERMISSIONS.HEALTH_READ},{label:'Audit Logs',to:'/audit-logs',icon:FileClock,permission:PERMISSIONS.AUDIT_READ},{label:'Catalog & Plans',to:'/catalog-plans',icon:Gauge,permission:PERMISSIONS.CATALOG_READ},
]
export function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){const{path}=useRouter();const auth=useAuth();return <><div className={`mobile-overlay ${open?'visible':''}`} onClick={onClose}/><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark">B</div><div>BetterSnap<span>.AI</span><small>Super Admin</small></div><button className="mobile-close" onClick={onClose} aria-label="Close navigation"><X/></button></div><nav>{nav.filter(item=>auth.hasPermission(item.permission)).map(({label,to,icon:Icon})=><Link key={to} to={to} onClick={onClose} className={path===to||(to!=='/dashboard'&&path.startsWith(`${to}/`))?'active':''}><Icon size={19}/>{label}</Link>)}</nav><div className="sidebar-bottom"><div className="system-pill"><span/>Authorization UI active</div></div></aside></>}
export function Header({onMenu}:{onMenu:()=>void}){const{path,navigate}=useRouter();const auth=useAuth();const[menu,setMenu]=useState(false);const label=path.split('/').filter(Boolean).map(x=>x.replaceAll('-',' '));const logout=async()=>{await auth.logout();navigate('/login')};const initials=auth.identity?.name.split(' ').map(x=>x[0]).join('').slice(0,2)||'AD';return <header className="topbar"><button className="menu-button" onClick={onMenu} aria-label="Open navigation"><Menu/></button><div className="breadcrumbs"><Link to="/dashboard">Admin</Link><span>/</span><strong>{label[0]||'Dashboard'}</strong>{label[1]&&<><span>/</span><strong>{label[1]}</strong></>}</div><div className="header-actions"><div className="user-menu-wrap"><button className="user-button" onClick={()=>setMenu(!menu)} aria-expanded={menu}><span className="avatar">{initials}</span><span className="user-copy"><strong>{auth.identity?.name}</strong><small>{auth.identity?.roles.join(', ')||'No admin role'}</small></span><ChevronDown size={16}/></button>{menu&&<div className="user-dropdown"><div><strong>{auth.identity?.name}</strong><small>{auth.identity?.email}</small></div><button onClick={logout}><LogOut/>Log out</button></div>}</div></div></header>}
export function AppShell({children}:{children:ReactNode}){const[sidebar,setSidebar]=useState(false);return <div className="app-shell"><Sidebar open={sidebar} onClose={()=>setSidebar(false)}/><div className="app-main"><Header onMenu={()=>setSidebar(true)}/><main>{children}</main></div></div>}
