import { AlertCircle, Check, ChevronLeft, ChevronRight, Inbox, LoaderCircle, Search, ShieldAlert, X } from 'lucide-react'
import { createContext, useContext, useState, type ReactNode } from 'react'

export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }
export function StatusBadge({ status }: { status: string }) { return <span className={`badge badge-${status}`}><span />{status.replaceAll('_', ' ')}</span> }
export function SearchFilterBar({ value, onChange, placeholder = 'Search…', children }: { value: string; onChange: (value: string) => void; placeholder?: string; children?: ReactNode }) { return <div className="filter-bar"><label className="search"><Search size={17}/><span className="sr-only">Search</span><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/></label>{children}</div> }
export function Pagination({ page = 1, totalPages = 1, onChange = () => {} }: { page?: number; totalPages?: number; onChange?: (page: number) => void }) { return <nav className="pagination" aria-label="Pagination"><button className="icon-button" disabled={page <= 1} onClick={() => onChange(page - 1)} aria-label="Previous page"><ChevronLeft size={17}/></button><span>Page <strong>{page}</strong> of {totalPages}</span><button className="icon-button" disabled={page >= totalPages} onClick={() => onChange(page + 1)} aria-label="Next page"><ChevronRight size={17}/></button></nav> }
export function LoadingState({ label = 'Loading data…' }: { label?: string }) { return <div className="state"><LoaderCircle className="spin"/><h3>{label}</h3></div> }
export function EmptyState({ title = 'Nothing here yet', description = 'There are no records to display.' }: { title?: string; description?: string }) { return <div className="state"><Inbox/><h3>{title}</h3><p>{description}</p></div> }
export function ErrorState({ retry, title = "We couldn't load this page", description = 'Something went wrong. Please try again.' }: { retry?: () => void; title?: string; description?: string }) { return <div className="state"><AlertCircle/><h3>{title}</h3><p>{description}</p>{retry && <button className="button secondary" onClick={retry}>Try again</button>}</div> }
export function ForbiddenState() { return <div className="state"><ShieldAlert/><h3>Access restricted</h3><p>You don't have permission to view this area.</p></div> }

export interface Column<T> { key: string; header: string; render: (row: T) => ReactNode; className?: string }
export function DataTable<T>({ columns, rows, getRowKey, onRowClick, emptyTitle }: { columns: Column<T>[]; rows: T[]; getRowKey: (row: T) => string; onRowClick?: (row: T) => void; emptyTitle?: string }) {
  if (!rows.length) return <EmptyState title={emptyTitle}/>
  return <div className="table-scroll"><table><thead><tr>{columns.map(c => <th key={c.key} className={c.className}>{c.header}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={getRowKey(row)} className={onRowClick ? 'clickable' : ''} onClick={() => onRowClick?.(row)}>{columns.map(c => <td key={c.key} className={c.className}>{c.render(row)}</td>)}</tr>)}</tbody></table></div>
}

export function ConfirmActionDialog({ open, title, description, confirmLabel = 'Confirm', destructive, onConfirm, onClose }: { open: boolean; title: string; description: string; confirmLabel?: string; destructive?: boolean; onConfirm: () => void; onClose: () => void }) { if (!open) return null; return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><div className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="dialog-title" onMouseDown={e => e.stopPropagation()}><button className="dialog-close" onClick={onClose} aria-label="Close"><X/></button><div className={`dialog-icon ${destructive ? 'danger' : ''}`}><AlertCircle/></div><h2 id="dialog-title">{title}</h2><p>{description}</p><div className="dialog-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className={`button ${destructive ? 'danger-button' : ''}`} onClick={onConfirm}>{confirmLabel}</button></div></div></div> }
export function ReasonRequiredDialog({ open, title, onConfirm, onClose }: { open: boolean; title: string; onConfirm: (reason: string) => void; onClose: () => void }) { const [reason, setReason] = useState(''); if (!open) return null; return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true"><h2>{title}</h2><p>Provide a reason for the audit log.</p><label className="field"><span>Reason</span><textarea value={reason} onChange={e => setReason(e.target.value)} rows={4} placeholder="Enter a clear reason…"/></label><div className="dialog-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={!reason.trim()} onClick={() => onConfirm(reason)}>Continue</button></div></div></div> }

type Toast = { id: number; message: string; type: 'success' | 'error' }
const ToastContext = createContext<{ showToast: (message: string, type?: Toast['type']) => void }>({ showToast: () => undefined })
export function ToastProvider({ children }: { children: ReactNode }) { const [toasts, setToasts] = useState<Toast[]>([]); const showToast = (message: string, type: Toast['type'] = 'success') => { const id = Date.now(); setToasts(t => [...t, { id, message, type }]); window.setTimeout(() => setToasts(t => t.filter(x => x.id !== id)), 3500) }; return <ToastContext.Provider value={{ showToast }}>{children}<div className="toast-region" aria-live="polite">{toasts.map(t => <div className={`toast ${t.type}`} key={t.id}>{t.type === 'success' ? <Check/> : <AlertCircle/>}{t.message}</div>)}</div></ToastContext.Provider> }
export const useToast = () => useContext(ToastContext)
