import { useCallback, useState } from 'react'
import { DataTable, ErrorState, LoadingState, PageHeader, Pagination, StatusBadge } from '../../components'
import { useApiResource } from '../../lib/useApiResource'
import { billingService, creditsService, type SuperAdminCreditEntry, type SuperAdminPayment, type SuperAdminSubscription } from '../../services'
import { DataSourceBadge } from '../dashboard/DashboardPage'

export function PaymentsPage(){const[page,setPage]=useState(1),limit=50;const load=useCallback(()=>billingService.listPayments({limit,offset:(page-1)*limit}),[page]);const s=useApiResource(load,page);if(s.loading&&!s.data)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;const d=s.data.data;return <><PageHeader title="Payments" description="Live credit-grant payment records. Refunding money through Stripe is not available; restoring BetterSnap credits is a separate action." action={<DataSourceBadge type="live"/>}/><section className="card table-card"><DataTable<SuperAdminPayment> rows={d.payments} getRowKey={x=>x.transaction_id} columns={[{key:'id',header:'Transaction',render:x=><span className="mono">{x.transaction_id}</span>},{key:'user',header:'User',render:x=><><strong>{x.email}</strong><small className="mono">{x.user_id}</small></>},{key:'stripe',header:'Stripe customer',render:x=>x.stripe_customer_id||'Not recorded'},{key:'credits',header:'Credits granted',render:x=>x.credits_granted.toLocaleString()},{key:'type',header:'Type',render:x=>x.type},{key:'created',header:'Created',render:x=>new Date(x.created_at).toLocaleString()}]}/><div className="table-footer"><span>{d.total} records</span><Pagination page={page} totalPages={Math.max(1,Math.ceil(d.total/limit))} onChange={setPage}/></div></section></>}

export function SubscriptionsPage(){const[page,setPage]=useState(1),limit=50;const load=useCallback(()=>billingService.listSubscriptions({limit,offset:(page-1)*limit}),[page]);const s=useApiResource(load,page);if(s.loading&&!s.data)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;const d=s.data.data;return <><PageHeader title="Subscriptions" description="Live platform subscriptions. Admin cancel/reactivate actions are not implemented." action={<DataSourceBadge type="live"/>}/><section className="card table-card"><DataTable<SuperAdminSubscription> rows={d.subscriptions} getRowKey={x=>x.user_id} columns={[{key:'user',header:'User',render:x=><><strong>{x.email}</strong><small className="mono">{x.user_id}</small></>},{key:'type',header:'Type',render:x=>x.subscription_type},{key:'plan',header:'Plan',render:x=>x.subscription_plan},{key:'credits',header:'Monthly credits',render:x=>x.monthly_credits_remaining.toLocaleString()},{key:'start',header:'Start',render:x=>x.start?new Date(x.start).toLocaleDateString():'Not recorded'},{key:'end',header:'End',render:x=>x.end?new Date(x.end).toLocaleDateString():'Not recorded'},{key:'cancel',header:'Cancel at',render:x=>x.cancel_at?new Date(x.cancel_at).toLocaleDateString():'No cancellation'},{key:'payment',header:'Payment',render:x=><StatusBadge status={x.payment_failed?'failed':'healthy'}/>}]}/><div className="table-footer"><span>{d.total} subscriptions</span><Pagination page={page} totalPages={Math.max(1,Math.ceil(d.total/limit))} onChange={setPage}/></div></section></>}

export function CreditsPage(){const[userId,setUserId]=useState('');const[type,setType]=useState('');const[page,setPage]=useState(1),limit=50;const load=useCallback(()=>creditsService.list({user_id:userId||undefined,type:type||undefined,limit,offset:(page-1)*limit}),[userId,type,page]);const s=useApiResource(load,`${userId}|${type}|${page}`);if(s.loading&&!s.data)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;const d=s.data.data;return <><PageHeader title="Credit Ledger" description="Live, platform-wide immutable credit transactions." action={<DataSourceBadge type="live"/>}/><section className="card table-card"><div className="filter-bar"><input value={userId} onChange={e=>{setUserId(e.target.value);setPage(1)}} placeholder="Filter user ID"/><input value={type} onChange={e=>{setType(e.target.value);setPage(1)}} placeholder="Filter transaction type"/></div><DataTable<SuperAdminCreditEntry> rows={d.entries} getRowKey={x=>x.transaction_id} columns={[{key:'id',header:'Transaction',render:x=><span className="mono">{x.transaction_id}</span>},{key:'user',header:'User',render:x=><><strong>{x.email}</strong><small className="mono">{x.user_id}</small></>},{key:'amount',header:'Amount',render:x=><strong className={x.amount>=0?'delta-positive':'delta-negative'}>{x.amount>0?'+':''}{x.amount}</strong>},{key:'type',header:'Type',render:x=>x.type},{key:'job',header:'Job',render:x=>x.job_id||'Not related'},{key:'created',header:'Created',render:x=>new Date(x.created_at).toLocaleString()}]}/><div className="table-footer"><span>{d.total} entries</span><Pagination page={page} totalPages={Math.max(1,Math.ceil(d.total/limit))} onChange={setPage}/></div></section></>}
