"""Canonical BetterSnap category / attire / background catalog — the SINGLE source
of truth for both deploy units:

  • Azure Functions app imports it as `shared.catalog` (validation in /jobs/submit,
    and it is served to the frontend via GET /catalog so the UI never hardcodes).
  • The inference container imports it as `catalog` (the Dockerfile COPYs this file
    AND catalog_data.py to /app/); main.py builds every prompt from it.

The DATA now lives in catalog_data.py (auto-generated by scripts/gen_catalog.py from
data/catalog_seed.json). This module keeps the lookup/validation LOGIC. Attires are
GENDER-SPECIFIC lists (male / female / other) — a different set per gender, not one id
with three phrasings — so lookups take the user's gender. Backgrounds are shared per
category. 'neutral'/unknown gender maps to the 'other' set.

Each category (in catalog_data.CATEGORY_CATALOG):
  type        "professional" | "personal"
  label       display name
  lead        photograph lead-in
  lighting    optional list overriding the global lighting rotation
  custom      True only for custom_scene (user types the scene; no attire/bg menu)
  attires     { gender: { attire_key: {label, phrase, image_key, ref, sort_order} } }
  backgrounds { bg_key: {label, phrase, image_key, ref, sort_order} }
"""

# ── Cross-layer storage paths (producer↔consumer contract) ───────────────────
# Per-user face crops the trainer writes and the inference container reads as
# IP-Adapter references. Producer (function_app) writes inputs/<user_id>/<CROP_SUBDIR>/;
# consumer (main.py._get_ref_faces) reads the same. Defined ONCE here — the cross-layer
# SSOT file COPYd into the inference image — so the path can never drift between units.
CROP_SUBDIR = "input/crop_upperbody"


# ── Identity vocabulary (shared by TRAINING and GENERATION) ──────────────────
# The rare DreamBooth trigger token. Every per-user LoRA is trained with it in the
# instance prompt, and main.py bakes it into every generation prompt; without it the
# adapter loads but is never invoked → generic strangers.
IDENTITY_TRIGGER = "ohwx"

# gender → class word. This word MUST be identical at training time
# ("a photo of ohwx woman") and at generation time ("ohwx woman"), or the token the
# adapter was trained against is not the token the prompt fires. That is why it lives
# here, in the one module BOTH deploy units import, rather than being spelled out
# separately in function_app.py and main.py.
SUBJECT_NOUN = {"female": "woman", "male": "man", "neutral": "person"}


def normalize_gender(g: str) -> str:
    """Map any gender input to one of {'female','male','neutral'}. Never assumes a
    default — absent/unknown → 'neutral' (gender-neutral attire + subject noun)."""
    g = (g or "").strip().lower()
    if g in ("female", "woman", "women", "f", "she/her"):
        return "female"
    if g in ("male", "man", "men", "m", "he/him"):
        return "male"
    return "neutral"


def class_word(gender: str) -> str:
    """The DreamBooth class word for this user: woman | man | person."""
    return SUBJECT_NOUN[normalize_gender(gender)]


def gender_from_class_word(cw: str) -> str:
    """Reverse-map: class_word (woman|man|person) → gender (female|male|neutral).
    Returns the gender if the class_word is recognized, else None (for legacy/corrupt rows)."""
    if cw in ("woman",):
        return "female"
    if cw in ("man",):
        return "male"
    if cw in ("person",):
        return "neutral"
    return None  # legacy/NULL/unrecognized


def instance_prompt(class_word_: str) -> str:
    """What the LoRA is trained to bind the trigger token to."""
    return f"a photo of {IDENTITY_TRIGGER} {class_word_}"


def class_prompt(class_word_: str) -> str:
    """The prior-preservation anchor. Pins the GENERIC class in place so the trigger
    token can only encode what makes THIS person different from it — i.e. their face."""
    return f"a photo of a {class_word_}"


# ── Catalog data (generated) ─────────────────────────────────────────────────
# Works both as a package (shared.catalog_data, in the Functions app) and top-level
# (catalog_data, COPYd next to catalog.py in the inference container image).
try:
    from .catalog_data import CATEGORY_CATALOG  # type: ignore
except ImportError:  # pragma: no cover - container/top-level import path
    from catalog_data import CATEGORY_CATALOG  # type: ignore

# Attire data is keyed by these three genders. The identity/training path uses
# {female, male, neutral}; for ATTIRE selection 'neutral' resolves to the 'other' set.
ATTIRE_GENDERS = ("male", "female", "other")


def _attire_gender(gender_key: str) -> str:
    """Map any gender input to the attire-data gender key: male | female | other."""
    g = normalize_gender(gender_key)
    return "male" if g == "male" else "female" if g == "female" else "other"


# ── Lookups / validation (used by function_app.submit_job) ────────────────────
def category_type(category: str):
    c = CATEGORY_CATALOG.get(category)
    return c["type"] if c else None


def _attires_for_gender(category: str, gender_key: str) -> dict:
    return CATEGORY_CATALOG.get(category, {}).get("attires", {}).get(_attire_gender(gender_key), {})


def valid_attire_ids(category: str, gender: str = None) -> set:
    """Attire keys for a category. With a gender, only that gender's set; without a
    gender, the union across all genders (a defensive existence check)."""
    attires = CATEGORY_CATALOG.get(category, {}).get("attires", {})
    if gender is not None:
        return set(attires.get(_attire_gender(gender), {}).keys())
    ids = set()
    for by_key in attires.values():
        ids.update(by_key.keys())
    return ids


def valid_background_ids(category: str) -> set:
    return set(CATEGORY_CATALOG.get(category, {}).get("backgrounds", {}).keys())


def public_catalog() -> list:
    """Display catalog served to the frontend via GET /catalog. Attires are gender-specific,
    so each category carries `attires_by_gender` (the new gender-aware picker) AND a flat
    `attires` = the 'other' set for backward-compatibility with the pre-gender frontend.
    Each option carries a category-qualified `ref` ('category.option') + an `image_key`."""
    def _opt(o):
        return {"id": o["ref"].split(".", 1)[1], "ref": o["ref"], "label": o["label"],
                "image_key": o.get("image_key")}

    out = []
    for key, c in sorted(CATEGORY_CATALOG.items(), key=lambda kv: (kv[1].get("sort_order", 0), kv[0])):
        attires = c.get("attires", {})
        by_gender = {g: [_opt(o) for o in sorted(attires.get(g, {}).values(),
                                                 key=lambda o: o.get("sort_order", 0))]
                     for g in ATTIRE_GENDERS}
        out.append({
            "id": key,
            "type": c["type"],
            "label": c["label"],
            "custom": bool(c.get("custom")),
            "attires": by_gender.get("other", []),          # back-compat flat list
            "attires_by_gender": by_gender,                  # gender-aware
            "backgrounds": [_opt(o) for o in sorted(c.get("backgrounds", {}).values(),
                                                    key=lambda o: o.get("sort_order", 0))],
        })
    return out


# ── Category-qualified refs ("category.option") for the GLOBAL picker ──────────
# Selections span categories, so every attire/background is addressed as a ref.
def split_ref(ref: str):
    cat, _, opt = (ref or "").partition(".")
    return cat, opt


def valid_attire_ref(ref: str, gender: str = None) -> bool:
    """Is this attire ref real? With a gender, checks that gender's set (strict —
    used by submit_job); without, checks any gender (defensive, used by build_combos)."""
    cat, opt = split_ref(ref)
    return opt in valid_attire_ids(cat, gender)


def valid_background_ref(ref: str) -> bool:
    cat, opt = split_ref(ref)
    return opt in valid_background_ids(cat)


def ref_type(ref: str):
    cat, _ = split_ref(ref)
    return category_type(cat)


def attire_phrase_ref(ref: str, gender_key: str) -> str:
    cat, opt = split_ref(ref)
    return attire_phrase(cat, opt, gender_key)


def background_phrase_ref(ref: str) -> str:
    cat, opt = split_ref(ref)
    return background_phrase(cat, opt)


def lead_for_background_ref(ref: str) -> str:
    """Lead phrase (style) is DERIVED FROM THE BACKGROUND's category — a beach bg
    reads 'natural lifestyle portrait', an office bg 'corporate headshot', even if
    the attire came from a different category."""
    cat, _ = split_ref(ref)
    return lead_phrase(cat)


def lighting_for_background_ref(ref: str, default: list) -> list:
    """Lighting also follows the background (beach→golden, dark_studio→moody)."""
    cat, _ = split_ref(ref)
    return lighting_options(cat, default)


def _valid_unique(refs: list, validator) -> list:
    """Validated refs, de-duplicated, original order preserved. A duplicate selection would
    otherwise waste a combo slot (and coverage)."""
    seen, out = set(), []
    for r in (refs or []):
        if r not in seen and validator(r):
            seen.add(r)
            out.append(r)
    return out


def build_combos_global(attire_refs: list, background_refs: list) -> list:
    """Coverage-first ordering of the SELECTED attire × background product (spanning any
    categories). Invalid refs are dropped and duplicates removed.

    The generation loop takes combos[i % len(combos)] for i in range(image_count), so the
    ORDER decides what a short session shows. A naive attire-major product
    ([(a, b) for a in attires for b in backgrounds]) front-loads all of the FIRST attire's
    combos, so when image_count < len(combos) the later attires render ZERO images (bug B1).
    Instead we emit a diagonal-shifted permutation: the attire index advances every step and
    shifts each round. Every prefix therefore covers as many distinct attires + backgrounds as
    the count allows — all attires by pick n_attires, all backgrounds by pick n_backgrounds —
    while the FULL list is still the complete product, so a large image_count cycles through
    every combo exactly as before. Returns (attire_ref, background_ref) tuples."""
    a_sel = _valid_unique(attire_refs, valid_attire_ref)
    b_sel = _valid_unique(background_refs, valid_background_ref)
    n_a, n_b = len(a_sel), len(b_sel)
    if n_a == 0 or n_b == 0:
        return []
    return [(a_sel[(b + r) % n_a], b_sel[b]) for r in range(n_a) for b in range(n_b)]


def attire_phrase(category: str, attire_id: str, gender_key: str) -> str:
    """Gender-specific attire phrase. Tries the requested gender, then 'other', then any
    gender that has the key, so a stale/cross-gender ref still resolves to something sane."""
    attires = CATEGORY_CATALOG.get(category, {}).get("attires", {})
    want = _attire_gender(gender_key)
    for g in (want, "other", "male", "female"):
        a = attires.get(g, {}).get(attire_id)
        if a:
            return a["phrase"]
    return "professional attire"


def background_phrase(category: str, background_id: str) -> str:
    b = CATEGORY_CATALOG.get(category, {}).get("backgrounds", {}).get(background_id)
    return b["phrase"] if b else "against a neutral studio backdrop"


def lead_phrase(category: str) -> str:
    return CATEGORY_CATALOG.get(category, {}).get(
        "lead", "A professional headshot photograph of"
    )


def lighting_options(category: str, default: list) -> list:
    """Per-category lighting override (moody/warm/golden) or the global default."""
    return CATEGORY_CATALOG.get(category, {}).get("lighting") or default
