"""Generate shared/catalog_data.py from data/catalog_seed.json.

The seed (authored by hand — only prompt phrases) is the single source of truth. Every
key is DERIVED from the label so filenames/refs never drift:
    attire_key / bg_key = snake(label)        e.g. "Navy Suit & Tie" -> navy_suit_tie
    ref                 = "<category>.<key>"
    image_key           = kebab(label)        e.g. "Navy Suit & Tie" -> navy-suit-tie
Image path is composed per gender by the API / container:
    /catalog/<gender>/<attires|backgrounds>/<image_key>_<gender>.jpg

Run from the backend dir:  python scripts/gen_catalog.py
It writes shared/catalog_data.py (imported by shared/catalog.py). Also used by
scripts/seed_catalog.py to upsert the DB, so both consumers stay in sync.
"""
import json
import os
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SEED = ROOT / "data" / "catalog_seed.json"
OUT = ROOT / "shared" / "catalog_data.py"

GENDERS = ("male", "female", "other")


def kebab(s: str) -> str:
    """'Navy Suit & Tie' -> 'navy-suit-tie' (matches the /public/catalog filenames)."""
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def snake(s: str) -> str:
    return kebab(s).replace("-", "-").replace("-", "_")


def build_category(key: str, c: dict) -> dict:
    out = {
        "type": c["category_type"],
        "label": c["label"],
        "lead": c["lead_phrase"],
        "lighting": c.get("lighting"),
        "custom": bool(c.get("custom", False)),
        "sort_order": c.get("sort_order", 0),
        "attires": {},
        "backgrounds": {},
    }
    for g in GENDERS:
        out["attires"][g] = {}
        for i, a in enumerate(c.get("attires", {}).get(g, [])):
            label = a["label"]
            akey = snake(label)
            out["attires"][g][akey] = {
                "label": label,
                "phrase": a["phrase"],
                "image_key": kebab(label),
                "ref": f"{key}.{akey}",
                "sort_order": i,
            }
    for i, b in enumerate(c.get("backgrounds", [])):
        label = b["label"]
        bkey = snake(label)
        out["backgrounds"][bkey] = {
            "label": label,
            "phrase": b["phrase"],
            "image_key": kebab(label),
            "ref": f"{key}.{bkey}",
            "sort_order": i,
        }
    return out


def main():
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    catalog = {}
    for key, c in seed.items():
        if key.startswith("_"):
            continue
        catalog[key] = build_category(key, c)

    header = (
        '"""AUTO-GENERATED by scripts/gen_catalog.py from data/catalog_seed.json — DO NOT EDIT.\n'
        "Gender-aware category/attire/background data. shared/catalog.py imports CATEGORY_CATALOG\n"
        "from here and provides the lookup/validation functions the Functions app + inference\n"
        'container use. Re-run the generator after editing the seed."""\n\n'
    )
    body = "CATEGORY_CATALOG = " + _pyrepr(catalog) + "\n"
    OUT.write_text(header + body, encoding="utf-8")

    # Quick summary for the operator.
    n_cat = len(catalog)
    n_att = sum(len(catalog[c]["attires"][g]) for c in catalog for g in GENDERS)
    n_bg = sum(len(catalog[c]["backgrounds"]) for c in catalog)
    print(f"WROTE {OUT}")
    print(f"categories={n_cat}  attires(all genders)={n_att}  backgrounds={n_bg}")


def _pyrepr(obj, indent=0):
    """Deterministic, readable Python-literal dump (stable ordering, no imports needed)."""
    sp = "    " * indent
    sp2 = "    " * (indent + 1)
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = []
        for k, v in obj.items():
            items.append(f"{sp2}{k!r}: {_pyrepr(v, indent + 1)}")
        return "{\n" + ",\n".join(items) + f",\n{sp}}}"
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = [f"{sp2}{_pyrepr(v, indent + 1)}" for v in obj]
        return "[\n" + ",\n".join(items) + f",\n{sp}]"
    return repr(obj)


if __name__ == "__main__":
    main()
