import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../../components'
import { backend } from '../../lib/api'
import { useApiResource } from '../../lib/useApiResource'
const labels:Record<string,[string,string]>={payments:['Payments','No payment-history or admin transaction endpoint is exposed.'],'audit-logs':['Audit Logs','No audit-log endpoint is exposed.']}
export function ResourcePage({resource}:{resource:string}){if(resource==='system-health')return <Health/>;if(resource==='catalog-plans')return <CatalogPlans/>;if(resource==='subscriptions')return <Subscription/>;if(resource==='credits')return <Credits/>;const [title,message]=labels[resource]||['Not Found','No matching frontend route exists.'];return <><PageHeader title={title} description="Backend capability required"/><section className="card"><EmptyState title="API endpoint unavailable" description={message}/></section></>}
function Health(){const s=useApiResource(backend.health);if(s.loading)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;return <><PageHeader title="System Health" description="Live response from GET /health"/><section className="resource-grid"><article className="metric-card"><span>API status</span><strong>{s.data.status}</strong><StatusBadge status={s.data.status==='OK'?'healthy':'failed'}/></article><article className="metric-card"><span>Face detection dependency</span><strong>{s.data.face_gate}</strong><StatusBadge status={s.data.face_gate==='ok'?'healthy':'failed'}/></article></section></>}
function CatalogPlans(){const s=useApiResource(()=>Promise.all([backend.catalog(),backend.plans()]));if(s.loading)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;const [catalog,plans]=s.data;return <><PageHeader title="Catalog & Plans" description="Live public catalog and plan configuration."/><section className="metrics"><article className="metric-card"><span>Categories</span><strong>{catalog.categories.length}</strong><small className="positive">GET /catalog</small></article><article className="metric-card"><span>Plans</span><strong>{plans.plans.length}</strong><small className="positive">GET /plans</small></article></section><section className="card info-card"><h2>Published plans</h2><dl>{plans.plans.map(x=><div key={x.key}><dt>{x.name}</dt><dd>{x.image_count} images · {x.credits_per_image} credit/image</dd></div>)}</dl></section></>}
function Subscription(){const s=useApiResource(backend.subscription);if(s.loading)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;return <><PageHeader title="Subscriptions" description="Live subscription for the authenticated account."/><section className="card info-card"><h2>Subscription status</h2><dl><div><dt>Plan</dt><dd>{s.data.subscription_plan||'None'}</dd></div><div><dt>Type</dt><dd>{s.data.subscription_type||'—'}</dd></div><div><dt>Credits</dt><dd>{s.data.credits_remaining}</dd></div><div><dt>Next renewal</dt><dd>{s.data.next_renewal||'—'}</dd></div><div><dt>Cancellation</dt><dd>{s.data.cancel_pending?'Pending':'No'}</dd></div><div><dt>Payment</dt><dd><StatusBadge status={s.data.payment_failed?'failed':'healthy'}/></dd></div></dl></section></>}
function Credits(){const s=useApiResource(backend.credits);if(s.loading)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;return <><PageHeader title="Credits" description="Live balance for the authenticated account."/><article className="metric-card"><span>Credits remaining</span><strong>{s.data.credits_remaining.toLocaleString()}</strong><small className="positive">GET /users/credits</small></article></>}
