import { RefreshCw } from 'lucide-react'
import { useCallback, useState } from 'react'
import { ErrorState, LoadingState, PageHeader, StatusBadge } from '../../components'
import { useApiResource } from '../../lib/useApiResource'
import { adminService, healthService } from '../../services'
import { DataSourceBadge } from '../dashboard/DashboardPage'

function componentStatus(value:string|Record<string,unknown>){if(typeof value==='string')return value;return String(value.status??'reported')}
export function SystemHealthPage(){const[lastUpdated,setLastUpdated]=useState<Date|null>(null);const load=useCallback(async()=>{const[basic,detailed]=await Promise.all([healthService.getHealth(),adminService.getSystemHealth()]);setLastUpdated(new Date());return{basic:basic.data,detailed:detailed.data}},[]);const s=useApiResource(load);if(s.loading&&!s.data)return <LoadingState/>;if(s.error||!s.data)return <ErrorState retry={s.reload}/>;const{basic,detailed}=s.data;const cards=[['Backend API',basic.status],['Face gate',basic.face_gate],['Azure SQL',componentStatus(detailed.sql)],['Blob Storage',componentStatus(detailed.blob)],['GPU active executions',String(detailed.gpu_active_executions)],['Queue depth',String(detailed.queue_depth)],['Failed jobs (24h)',String(detailed.failed_jobs_24h)]];return <><PageHeader title="System Health" description="Live public and authenticated SuperAdmin health checks." action={<div className="header-meta-actions"><DataSourceBadge type="live"/><button className="button secondary" onClick={s.reload}><RefreshCw size={14}/>Refresh</button></div>}/><p className="last-updated">Last updated: {lastUpdated?.toLocaleString()}</p><section className="component-health-grid">{cards.map(([name,value])=><article className="metric-card" key={name}><span>{name}</span><strong>{value}</strong>{name==='Backend API'||name==='Face gate'||name==='Azure SQL'||name==='Blob Storage'?<StatusBadge status={value.toLowerCase()==='ok'||value.toLowerCase()==='healthy'?'healthy':'warning'}/>:null}</article>)}</section></>}
